services:
    # Main service for running the fuzzer
    fuzzqlite:
        platform: linux/amd64
        build: .
        entrypoint: python3 /app/src/main.py
        container_name: fuzzqlite-run
        volumes:
            - ./bug_reproducers:/app/bug_reproducers
            - ./databases:/app/databases
        environment:
            - PYTHONPATH=/app/src
        working_dir: /app

    # Service for bash shell access
    shell:
        platform: linux/amd64
        build: .
        entrypoint: /bin/bash
        # Interactive mode
        stdin_open: true
        tty: true
        container_name: fuzzqlite-shell
        volumes:
            - ./bug_reproducers:/app/bug_reproducers
            - ./databases:/app/databases
        environment:
            - PYTHONPATH=/app/src
        working_dir: /app
        